### ISSUE TITLE
BlzSetSpecialEffectYaw does not work

### ISSUE THREAD

**Issue by terrioss** [Warcraft-III-Community-Edition/Issues#10]
BlzSetSpecialEffectYaw does not work, and doesnt give any error messages in console

**Comment by cipherxof** [comment]
Roll and Yaw seem to be swapped in 1.29. We'll fix it for the next update.

**Comment by TinkerWorX** [comment]
Can this be closed @cipherxof ?

**Comment by cipherxof** [comment]
Fixed for the next release.
