### ISSUE TITLE
Possible DestroyEffect bug

### ISSUE THREAD

**Issue by terrioss** [Warcraft-III-Community-Edition/Issues#11]
`DestroyEffect` native does not work in this code snippet
`call DestroyEffect(AddSpecialEffectTarget("Abilities\\Weapons\\LordofFlameMissile\\LordofFlameMissile",unit,"chest"))`

**Comment by cipherxof** [comment]
This is actually failing because it's missing the .mdl or .mdx extension. We'll need to support file extension agnostic model loading like we do with textures.

**Comment by cipherxof** [comment]
Fixed for the next release.
