### ISSUE TITLE
Blizzard.j.lua misses GUI instance api functions

### ISSUE THREAD

**Issue by Tasyen** [Warcraft-III-Community-Edition/Issues#15]
The Blizzard.j.lua included in W3CE-v0.1.1-alpha does not contain GUI instance api functions like:
BlzSetUnitIntegerFieldBJ
BlzSetUnitRealFieldBJ
BlzSetAbilityBooleanFieldBJ
BlzSetItemBooleanFieldBJ

[19:12:25 ERR Lua] [string "war3map.lua"]:28: attempt to call a nil value (global 'BlzSetUnitBooleanFieldBJ')

**Comment by TinkerWorX** [comment]
I think this can be closed right @cipherxof ?

**Comment by cipherxof** [comment]
Fixed for the next release.
