### ISSUE TITLE
SetMapName ignored in map list

### ISSUE THREAD

**Issue by terrioss** [Warcraft-III-Community-Edition/Issues#2]
Map name set by war3map.j is being ignored in map list

`call SetMapName("TRIGSTR_50000")`

https://cdn.discordapp.com/attachments/1037954156708773929/1053586405441417266/DotA_LoD_2.1e1.w3x

map link

**Comment by cipherxof** [comment]
The name matches in our client and in Reforged.

![image](https://user-images.githubusercontent.com/5994581/209454382-27bdc988-b58d-4824-8014-c3d0a8d369d1.png)

![image](https://user-images.githubusercontent.com/5994581/209454379-aa128b32-ee39-4efd-a0e0-67ead0c7fcb6.png)
