### ISSUE TITLE
Map crashing when started right after launching the game

### ISSUE THREAD

**Issue by terrioss** [Warcraft-III-Community-Edition/Issues#3]
How to reproduce the crash:
1. Launch the game
2. Start map

How to reproduce not crashing
1. Launch the game
2. Start few maps and/or browse the map list a bit
3. Start map

https://cdn.discordapp.com/attachments/1037954156708773929/1053586405441417266/DotA_LoD_2.1e1.w3x

map link

**Comment by cipherxof** [comment]
This map is crashing because the W3I file is made for TFT but the DOO file is made for Reforged. 

Need a way to determine if the DOO version without relying on the W3I.

**Comment by cipherxof** [comment]
Fixed for the next release.
