### ISSUE TITLE
GetUnitZ unimplemented

### ISSUE THREAD

**Issue by terrioss** [Warcraft-III-Community-Edition/Issues#8]
GetUnitZ isnt implemented yet, which can cause triggers using it for visual effects get broken

**Comment by cipherxof** [comment]
I have implemented this for the next release. https://github.com/Warcraft-III-Community-Edition/Launcher/pull/109

Although in the future I don't think we need issues created for missing natives.

**Comment by TinkerWorX** [comment]
> Although in the future I don't think we need issues created for missing natives.
I suggested this so we can more easily track what natives are important to do first.
